# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-12 20:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventName', models.CharField(max_length=100)),
                ('resourcePerson', models.CharField(max_length=200)),
                ('eventDate', models.DateField()),
                ('eventStartTime', models.TimeField()),
                ('eventEndTime', models.TimeField()),
                ('eventVenue', models.CharField(max_length=200)),
                ('eventRating', models.FloatField(default=0.0)),
                ('studentsRegistered', models.IntegerField(default=0)),
                ('ECE', models.BooleanField(default=False)),
                ('CSE', models.BooleanField(default=False)),
                ('EEE', models.BooleanField(default=False)),
                ('IT', models.BooleanField(default=False)),
                ('mechanical', models.BooleanField(default=False)),
                ('chemical', models.BooleanField(default=False)),
                ('civil', models.BooleanField(default=False)),
                ('timesViewed', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RegisteredEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventRating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('teacherCredits', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManager.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=100)),
                ('studentRollNumber', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('r^31\\d{2}265\\d{5}$')])),
                ('studentDept', models.CharField(max_length=100)),
                ('studentPassword', models.CharField(max_length=25)),
                ('studentCGPA', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(10.0)])),
                ('studentAttendance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacherName', models.CharField(max_length=100)),
                ('teacherDept', models.CharField(max_length=100)),
                ('teacherExperience', models.PositiveIntegerField()),
                ('teacherPassword', models.CharField(max_length=25)),
                ('teacherCredits', models.FloatField(default=0.0)),
            ],
        ),
        migrations.AddField(
            model_name='registeredevents',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManager.Student'),
        ),
        migrations.AddField(
            model_name='event',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventManager.Teacher'),
        ),
    ]
