# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0003_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentRollNumber',
            field=models.CharField(max_length=12),
        ),
    ]
