# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-01 05:06
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventManager', '0004_auto_20160801_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentAttendance',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentPassword',
            field=models.CharField(default='anits123*', max_length=25),
        ),
    ]
